# $schema: configuration_schema.json
telemetry:
  instrumentation:
    spans:
      mode: spec_compliant

coprocessor:
  url: http://localhost:3007
  supergraph:
    request:
      headers: true
      context: true
